# see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
# to check available agents
trigger:
- v0.6.0
- azure*

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- template: conda-build.yml
  parameters:
    name: Ubuntu_18_04_python36
    vmImage: 'ubuntu-18.04'
    py_maj: 3
    py_min: 6

- template: conda-build.yml
  parameters:
    name: Ubuntu_20_04_python36
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 6

- template:  conda-build.yml
  parameters:
    name: macOS_10_14_python36
    vmImage: 'macOS-10.14'
    py_maj: 3
    py_min: 6

- template:  conda-build.yml
  parameters:
    name: Windows_VS2019_python36
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 6
    conda_bld: 3.17

- template: conda-build.yml
  parameters:
    name: Ubuntu_18_04_python37
    vmImage: 'ubuntu-18.04'
    py_maj: 3
    py_min: 7

- template: conda-build.yml
  parameters:
    name: Ubuntu_20_04_python37
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 7

- template:  conda-build.yml
  parameters:
    name: macOS_10_14_python37
    vmImage: 'macOS-10.14'
    py_maj: 3
    py_min: 7

- template:  conda-build.yml
  parameters:
    name: Windows_VS2019_python37
    vmImage: 'windows-2019'
    py_maj: 3
    py_min: 7
    conda_bld: 3.17
