cmake -G "NMake Makefiles" ^
 -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DCMAKE_SYSTEM_PREFIX_PATH="%LIBRARY_PREFIX%" ^
 -DPython3_FIND_STRATEGY=LOCATION ^
 -DPython3_FIND_REGISTRY=NEVER ^
 -DOCC_INCLUDE_DIR="%LIBRARY_PREFIX%\include\opencascade" ^
 -DOCC_LIBRARY_DIR="%LIBRARY_PREFIX%\lib" ^
 -DCOLLADA_SUPPORT=OFF ^
 -DBUILD_EXAMPLES=OFF ^
 -DBUILD_GEOMSERVER=ON ^
 -DBUILD_CONVERT=ON ^
 -DBUILD_IFCPYTHON=ON ^
 -DBUILD_IFCGEOM=ON ^
 -DIFCXML_SUPPORT=ON ^
 -DMSVC_EXTRA_WARNINGS=OFF ^
 ./cmake
 if errorlevel 1 exit 1

nmake
if errorlevel 1 exit 1

nmake install
if errorlevel 1 exit 1
