{% set version = "0.6.0" %}

package:
  name: ifcopenshell
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  binary_relocation: false [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - ninja ==1.10.2
    - cmake
    - swig ==4.0.2

  host:
    - python {{ python }}
    - occt ==7.5.0
    - libboost
    - libxml2

  run:
    - python
    - occt ==7.5.0
    - libboost
    - libxml2
    - lark-parser
    - deepdiff

about:
  home: http://ifcopenshell.org
  license: LGPL
